tap "bramstein/webfonttools"
tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "koekeishiya/formulae"
tap "romkatv/powerlevel10k"

cask "firefox"
cask "postman"
cask "alfred"
cask "betterdiscord-installer"

brew "fastfetch"
brew "glib"
brew "findutils"
brew "git-crypt"
brew "python@3.9"
